# ============================================================
# WireGuard Server
# ============================================================

[Interface]
Address = <VPN_SERVER_IP>/24
ListenPort = <VPN_PORT>
PrivateKey = <VPN_SERVER_PRIVATE_KEY>

# ------------------------------------------------------------
# Peers
# ------------------------------------------------------------

# pc (<VPN_CLIENT_PC>)
[Peer]
PublicKey = <VPN_CLIENT_PC_PUBLIC_KEY>
AllowedIPs = <VPN_CLIENT_PC>/32

# phone (<VPN_CLIENT_PHONE>)
[Peer]
PublicKey = <VPN_CLIENT_PHONE_PUBLIC_KEY>
AllowedIPs = <VPN_CLIENT_PHONE>/32